apiVersion: v1
kind: Service
metadata:
  name: rincyapp-service
  labels:
    app: rincyapp
spec:
  selector:
    app: rincyapp
  type: NodePort
  ports:
  - port: 5000
    targetPort: http
    nodePort: 31163 #30000-32767
    protocol: TCP
    name: http